### ISSUE TITLE
Bad Gateway to worldbank.org

### ISSUE THREAD

**Issue by misspidgie** [stevecondylios/priceR#59]
inflation_dataframe <- retrieve_inflation_data("US")

Error:
In open.connection(con, "rb") :
  cannot open URL 'http://api.worldbank.org/v2/country?format=json': HTTP status was '502 Bad Gateway'

**Comment by stevecondylios** [comment]
Thanks for reporting. This looks like a problem with the world bank API server. Hopefully it resolves itself soon.

**Comment by stevecondylios** [comment]
The world bank docs say:

> The API supports both “http” and “https” protocols.

When I try http://api.worldbank.org/v2/country?format=json it redirects to https://api.worldbank.org/v2/country?format=json (note the http***s***), which works. But http doesn't work atm (without the redirect). 

So, for whatever reason, http doesn't work on the world bank API right now, but https does. It could be due to some temporary outage/problem on their servers, but it could also be a change they've made but not fully documented yet. So I will update priceR to use https. Will update this thread when ready.

**Comment by stevecondylios** [comment]
Made the fix, please reinstall the package via

```r
# (close existing R session and reopen a new R session)

devtools::install_github("stevecondylios/priceR")  
library(priceR)
retrieve_inflation_data("US")

```

Once tests pass I will upload the updated package to CRAN, but I think it should all work now..

**Comment by misspidgie** [comment]
This worked, thank you for the quick reply!

**Comment by stevecondylios** [comment]
Updated version is now on CRAN.
